DROP TABLE IF EXISTS deals;
DROP TABLE IF EXISTS menu_items;
DROP TABLE IF EXISTS burgers;
DROP TABLE IF EXISTS eateries;
DROP TABLE IF EXISTS days;


CREATE TABLE burgers (
  id SERIAL2 PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE days (
  id SERIAL2 PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE eateries (
  id SERIAL2 PRIMARY KEY,
  name VARCHAR(255)
);

CREATE TABLE menu_items (
  id SERIAL2 PRIMARY KEY,
  burger_id INT2 REFERENCES burgers(id) ON DELETE CASCADE,
  eatery_id INT2 REFERENCES eateries(id) ON DELETE CASCADE,
  price INT2
);

CREATE TABlE deals (
  id SERIAL2 PRIMARY KEY,
  name VARCHAR(255),
  menu_item_id INT2 REFERENCES menu_items(id) ON DELETE CASCADE,
  day_id INT2 REFERENCES days(id) ON DELETE CASCADE

)
